/**
 * Guards the committed program metadata.
 *
 * lib/metadata.json is generated by scripts/update-metadata.cjs, which runs on
 * `prebuild`. When an upstream `adds` tree returns null the generator yields an
 * empty category and writes it out, so a plain `npm run build` can silently
 * delete a whole breakdown and commit it. That happened: the 18 US benefit
 * entries were replaced with [], which made the benefits table show everything
 * as "Other Benefits".
 */

import { describe, it, expect } from "vitest";
import usMetadata from "../lib/metadata.json";
import ukMetadata from "../lib/metadata-uk.json";

describe.each([
  ["US", usMetadata, ["snap", "ssi", "social_security", "tanf"]],
  ["UK", ukMetadata, ["universal_credit", "child_benefit", "housing_benefit"]],
])("%s program metadata", (_name, metadata, expectedBenefits) => {
  it("lists benefits", () => {
    expect(metadata.benefits.length).toBeGreaterThan(0);
  });

  it("lists taxes", () => {
    expect(metadata.taxes.length).toBeGreaterThan(0);
  });

  it("includes the programs the breakdown is expected to name", () => {
    const names = metadata.benefits.map((b) => b.variable);
    for (const v of expectedBenefits) expect(names).toContain(v);
  });

  it("gives every entry a variable, entity and label", () => {
    for (const cat of ["benefits", "taxes"]) {
      for (const entry of metadata[cat]) {
        expect(entry.variable, `${cat} entry`).toBeTruthy();
        expect(entry.entity, entry.variable).toBeTruthy();
        expect(entry.label, entry.variable).toBeTruthy();
      }
    }
  });

  it("has no duplicate variables within a category", () => {
    for (const cat of ["benefits", "taxes"]) {
      const names = metadata[cat].map((e) => e.variable);
      expect(new Set(names).size, cat).toBe(names.length);
    }
  });
});
