import usMetadata from "./metadata.json";
import ukMetadata from "./metadata-uk.json";

export const US_REGIONS = [
  { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
  { code: "DC", name: "District of Columbia" }, { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" }, { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" }, { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" }, { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" }, { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" }, { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" }, { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" }, { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" }, { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" }, { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" }, { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" }, { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" }, { code: "NYC", name: "New York City" },
  { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
];

export const UK_REGIONS = [
  { code: "ENGLAND", name: "England" },
  { code: "SCOTLAND", name: "Scotland" },
  { code: "WALES", name: "Wales" },
  { code: "NORTHERN_IRELAND", name: "Northern Ireland" },
];


// Broad Rental Market Areas. The Local Housing Allowance cap on private rent is
// set per area, so leaving this unset silently applies the model's default of
// Maidstone to every household. On an £18,000 private rent that default caps
// support at £9,194 where Central London would pay the full £18,000, a
// difference of nearly £9,000 in net income. Fetched from the UK metadata API.
export const UK_BRMAS = [
  { code: "ASHFORD", name: "Ashford" },
  { code: "AYLESBURY", name: "Aylesbury" },
  { code: "BARNSLEY", name: "Barnsley" },
  { code: "BARROW_IN_FURNESS", name: "Barrow-in-Furness" },
  { code: "BASINGSTOKE", name: "Basingstoke" },
  { code: "BATH", name: "Bath" },
  { code: "BEDFORD", name: "Bedford" },
  { code: "BIRMINGHAM", name: "Birmingham" },
  { code: "BLACK_COUNTRY", name: "Black Country" },
  { code: "BLACKWATER_VALLEY", name: "Blackwater Valley" },
  { code: "BOLTON_AND_BURY", name: "Bolton and Bury" },
  { code: "BOURNEMOUTH", name: "Bournemouth" },
  { code: "BRADFORD_SOUTH_DALES", name: "Bradford & South Dales" },
  { code: "BRIGHTON_AND_HOVE", name: "Brighton and Hove" },
  { code: "BRISTOL", name: "Bristol" },
  { code: "BURY_ST_EDMUNDS", name: "Bury St Edmunds" },
  { code: "CAMBRIDGE", name: "Cambridge" },
  { code: "CANTERBURY", name: "Canterbury" },
  { code: "CENTRAL_GREATER_MANCHESTER", name: "Central Greater Manchester" },
  { code: "CENTRAL_LANCS", name: "Central Lancs" },
  { code: "CENTRAL_LONDON", name: "Central London" },
  { code: "CENTRAL_NORFOLK_NORWICH", name: "Central Norfolk & Norwich" },
  { code: "CHELMSFORD", name: "Chelmsford" },
  { code: "CHELTENHAM", name: "Cheltenham" },
  { code: "CHERWELL_VALLEY", name: "Cherwell Valley" },
  { code: "CHESTERFIELD", name: "Chesterfield" },
  { code: "CHICHESTER", name: "Chichester" },
  { code: "CHILTERNS", name: "Chilterns" },
  { code: "COLCHESTER", name: "Colchester" },
  { code: "COVENTRY", name: "Coventry" },
  { code: "CRAWLEY_REIGATE", name: "Crawley & Reigate" },
  { code: "DARLINGTON", name: "Darlington" },
  { code: "DERBY", name: "Derby" },
  { code: "DONCASTER", name: "Doncaster" },
  { code: "DOVER_SHEPWAY", name: "Dover-Shepway" },
  { code: "DURHAM", name: "Durham" },
  { code: "EAST_CHESHIRE", name: "East Cheshire" },
  { code: "EAST_LANCS", name: "East Lancs" },
  { code: "EAST_THAMES_VALLEY", name: "East Thames Valley" },
  { code: "EASTBOURNE", name: "Eastbourne" },
  { code: "EASTERN_STAFFORDSHIRE", name: "Eastern Staffordshire" },
  { code: "EXETER", name: "Exeter" },
  { code: "FYLDE_COAST", name: "Fylde Coast" },
  { code: "GLOUCESTER", name: "Gloucester" },
  { code: "GRANTHAM_NEWARK", name: "Grantham & Newark" },
  { code: "GREATER_LIVERPOOL", name: "Greater Liverpool" },
  { code: "GRIMSBY", name: "Grimsby" },
  { code: "GUILDFORD", name: "Guildford" },
  { code: "HALIFAX", name: "Halifax" },
  { code: "HARLOW_STORTFORD", name: "Harlow & Stortford" },
  { code: "HARROGATE", name: "Harrogate" },
  { code: "HEREFORDSHIRE", name: "Herefordshire" },
  { code: "HIGH_WEALD", name: "High Weald" },
  { code: "HULL_EAST_RIDING", name: "Hull & East Riding" },
  { code: "HUNTINGDON", name: "Huntingdon" },
  { code: "INNER_EAST_LONDON", name: "Inner East London" },
  { code: "INNER_NORTH_LONDON", name: "Inner North London" },
  { code: "INNER_SOUTH_EAST_LONDON", name: "Inner South East London" },
  { code: "INNER_SOUTH_WEST_LONDON", name: "Inner South West London" },
  { code: "INNER_WEST_LONDON", name: "Inner West London" },
  { code: "IPSWICH", name: "Ipswich" },
  { code: "ISLE_OF_WIGHT", name: "Isle of Wight" },
  { code: "KENDAL", name: "Kendal" },
  { code: "KERNOW_WEST", name: "Kernow West" },
  { code: "KINGS_LYNN", name: "Kings Lynn" },
  { code: "KIRKLEES", name: "Kirklees" },
  { code: "LANCASTER", name: "Lancaster" },
  { code: "LEEDS", name: "Leeds" },
  { code: "LEICESTER", name: "Leicester" },
  { code: "LINCOLN", name: "Lincoln" },
  { code: "LINCOLNSHIRE_FENS", name: "Lincolnshire Fens" },
  { code: "LOWESTOFT_GREAT_YARMOUTH", name: "Lowestoft & Great Yarmouth" },
  { code: "LUTON", name: "Luton" },
  { code: "MAIDSTONE", name: "Maidstone" },
  { code: "MEDWAY_SWALE", name: "Medway & Swale" },
  { code: "MENDIP", name: "Mendip" },
  { code: "MID_EAST_DEVON", name: "Mid & East Devon" },
  { code: "MID_WEST_DORSET", name: "Mid & West Dorset" },
  { code: "MID_STAFFS", name: "Mid Staffs" },
  { code: "MILTON_KEYNES", name: "Milton Keynes" },
  { code: "NEWBURY", name: "Newbury" },
  { code: "NORTH_CHESHIRE", name: "North Cheshire" },
  { code: "NORTH_CORNWALL_DEVON_BORDERS", name: "North Cornwall & Devon Borders" },
  { code: "NORTH_CUMBRIA", name: "North Cumbria" },
  { code: "NORTH_DEVON", name: "North Devon" },
  { code: "NORTH_NOTTINGHAM", name: "North Nottingham" },
  { code: "NORTH_WEST_KENT", name: "North West Kent" },
  { code: "NORTH_WEST_LONDON", name: "North West London" },
  { code: "NORTHAMPTON", name: "Northampton" },
  { code: "NORTHANTS_CENTRAL", name: "Northants Central" },
  { code: "NORTHUMBERLAND", name: "Northumberland" },
  { code: "NOTTINGHAM", name: "Nottingham" },
  { code: "OLDHAM_ROCHDALE", name: "Oldham & Rochdale" },
  { code: "OUTER_EAST_LONDON", name: "Outer East London" },
  { code: "OUTER_NORTH_EAST_LONDON", name: "Outer North East London" },
  { code: "OUTER_NORTH_LONDON", name: "Outer North London" },
  { code: "OUTER_SOUTH_EAST_LONDON", name: "Outer South East London" },
  { code: "OUTER_SOUTH_LONDON", name: "Outer South London" },
  { code: "OUTER_SOUTH_WEST_LONDON", name: "Outer South West London" },
  { code: "OUTER_WEST_LONDON", name: "Outer West London" },
  { code: "OXFORD", name: "Oxford" },
  { code: "PEAKS_DALES", name: "Peaks & Dales" },
  { code: "PETERBOROUGH", name: "Peterborough" },
  { code: "PLYMOUTH", name: "Plymouth" },
  { code: "PORTSMOUTH", name: "Portsmouth" },
  { code: "READING", name: "Reading" },
  { code: "RICHMOND_HAMBLETON", name: "Richmond & Hambleton" },
  { code: "ROTHERHAM", name: "Rotherham" },
  { code: "RUGBY_EAST", name: "Rugby & East" },
  { code: "SALISBURY", name: "Salisbury" },
  { code: "SCARBOROUGH", name: "Scarborough" },
  { code: "SCUNTHORPE", name: "Scunthorpe" },
  { code: "SHEFFIELD", name: "Sheffield" },
  { code: "SHROPSHIRE", name: "Shropshire" },
  { code: "SOLIHULL", name: "Solihull" },
  { code: "SOUTH_CHESHIRE", name: "South Cheshire" },
  { code: "SOUTH_DEVON", name: "South Devon" },
  { code: "SOUTH_EAST_HERTS", name: "South East Herts" },
  { code: "SOUTH_WEST_ESSEX", name: "South West Essex" },
  { code: "SOUTH_WEST_HERTS", name: "South West Herts" },
  { code: "SOUTHAMPTON", name: "Southampton" },
  { code: "SOUTHEND", name: "Southend" },
  { code: "SOUTHERN_GREATER_MANCHESTER", name: "Southern Greater Manchester" },
  { code: "SOUTHPORT", name: "Southport" },
  { code: "ST_HELENS", name: "St Helens" },
  { code: "STAFFORDSHIRE_NORTH", name: "Staffordshire North" },
  { code: "STEVENAGE_NORTH_HERTS", name: "Stevenage & North Herts" },
  { code: "SUNDERLAND", name: "Sunderland" },
  { code: "SUSSEX_EAST", name: "Sussex East" },
  { code: "SWINDON", name: "Swindon" },
  { code: "TAMESIDE_GLOSSOP", name: "Tameside & Glossop" },
  { code: "TAUNTON_WEST_SOMERSET", name: "Taunton & West Somerset" },
  { code: "TEESSIDE", name: "Teesside" },
  { code: "THANET", name: "Thanet" },
  { code: "TYNESIDE", name: "Tyneside" },
  { code: "WAKEFIELD", name: "Wakefield" },
  { code: "WALTON", name: "Walton" },
  { code: "WARWICKSHIRE_SOUTH", name: "Warwickshire South" },
  { code: "WEST_CHESHIRE", name: "West Cheshire" },
  { code: "WEST_CUMBRIA", name: "West Cumbria" },
  { code: "WEST_PENNINE", name: "West Pennine" },
  { code: "WEST_WILTSHIRE", name: "West Wiltshire" },
  { code: "WESTON_S_MARE", name: "Weston-S-Mare" },
  { code: "WIGAN", name: "Wigan" },
  { code: "WINCHESTER", name: "Winchester" },
  { code: "WIRRAL", name: "Wirral" },
  { code: "WOLDS_AND_COAST", name: "Wolds and Coast" },
  { code: "WORCESTER_NORTH", name: "Worcester North" },
  { code: "WORCESTER_SOUTH", name: "Worcester South" },
  { code: "WORTHING", name: "Worthing" },
  { code: "YEOVIL", name: "Yeovil" },
  { code: "YORK", name: "York" },
  { code: "BELFAST", name: "Belfast" },
  { code: "LOUGH_NEAGH_LOWER", name: "Lough Neagh Lower" },
  { code: "LOUGH_NEAGH_UPPER", name: "Lough Neagh Upper" },
  { code: "NORTH_NI", name: "North (NI)" },
  { code: "NORTH_WEST_NI", name: "North West (NI)" },
  { code: "SOUTH_NI", name: "South (NI)" },
  { code: "SOUTH_EAST_NI", name: "South East (NI)" },
  { code: "SOUTH_WEST_NI", name: "South West (NI)" },
  { code: "ABERDEEN_AND_SHIRE", name: "Aberdeen and Shire" },
  { code: "ARGYLL_AND_BUTE", name: "Argyll and Bute" },
  { code: "AYRSHIRES", name: "Ayrshires" },
  { code: "DUMFRIES_AND_GALLOWAY", name: "Dumfries and Galloway" },
  { code: "DUNDEE_AND_ANGUS", name: "Dundee and Angus" },
  { code: "EAST_DUNBARTONSHIRE", name: "East Dunbartonshire" },
  { code: "FIFE", name: "Fife" },
  { code: "FORTH_VALLEY", name: "Forth Valley" },
  { code: "GREATER_GLASGOW", name: "Greater Glasgow" },
  { code: "HIGHLAND_AND_ISLANDS", name: "Highland and Islands" },
  { code: "LOTHIAN", name: "Lothian" },
  { code: "NORTH_LANARKSHIRE", name: "North Lanarkshire" },
  { code: "PERTH_AND_KINROSS", name: "Perth and Kinross" },
  { code: "RENFREWSHIRE_AND_INVERCLYDE", name: "Renfrewshire and Inverclyde" },
  { code: "SCOTTISH_BORDERS", name: "Scottish Borders" },
  { code: "SOUTH_LANARKSHIRE", name: "South Lanarkshire" },
  { code: "WEST_DUNBARTONSHIRE", name: "West Dunbartonshire" },
  { code: "WEST_LOTHIAN", name: "West Lothian" },
  { code: "BLAENAU_GWENT", name: "Blaenau Gwent" },
  { code: "BRECON_AND_RADNOR", name: "Brecon and Radnor" },
  { code: "BRIDGEND", name: "Bridgend" },
  { code: "CAERPHILLY", name: "Caerphilly" },
  { code: "CARDIFF", name: "Cardiff" },
  { code: "CARMARTHENSHIRE", name: "Carmarthenshire" },
  { code: "CEREDIGION", name: "Ceredigion" },
  { code: "FLINTSHIRE", name: "Flintshire" },
  { code: "MERTHYR_CYNON", name: "Merthyr Cynon" },
  { code: "MONMOUTHSHIRE", name: "Monmouthshire" },
  { code: "NEATH_PORT_TALBOT", name: "Neath Port Talbot" },
  { code: "NEWPORT", name: "Newport" },
  { code: "NORTH_CLWYD", name: "North Clwyd" },
  { code: "NORTH_POWYS", name: "North Powys" },
  { code: "NORTH_WEST_WALES", name: "North West Wales" },
  { code: "PEMBROKESHIRE", name: "Pembrokeshire" },
  { code: "SOUTH_GWYNEDD", name: "South Gwynedd" },
  { code: "SWANSEA", name: "Swansea" },
  { code: "TAFF_RHONDDA", name: "Taff Rhondda" },
  { code: "TORFAEN", name: "Torfaen" },
  { code: "VALE_OF_GLAMORGAN", name: "Vale of Glamorgan" },
  { code: "WREXHAM", name: "Wrexham" },
];

export const DEFAULT_BRMA = "MAIDSTONE";

export const COUNTRIES = {
  uk: {
    id: "uk",
    name: "United Kingdom",
    currencySymbol: "\u00A3",
    apiPath: "/uk/calculate",
    // 2026-27 is the current UK tax year for this tool, with the three
    // following years available for forward-looking analysis.
    defaultYear: "2026",
    availableYears: ["2026", "2027", "2028", "2029"],
    defaultAge: 35,
    defaultRegion: "ENGLAND",
    regions: UK_REGIONS,
    regionLabel: "Country",
    regionVariable: "country",
    metadata: ukMetadata,
    entityContainers: {
      household: { key: "households", name: "your household" },
      benunit: { key: "benunits", name: "your benefit unit" },
    },
    tabs: ["summary", "taxes", "benefits"],
    hasCredits: false,
    hasStateCredits: false,
    // Disability drives the UC limited-capability element and, separately,
    // makes a childless benefit unit work-allowance eligible.
    hasDisability: true,
    hasPregnancy: false,
    hasESI: false,
    hasNYC: false,
    // Universal Credit maximum-amount elements the US config has no analogue
    // for. Each maps to an element in uc_maximum_amount in policyengine-uk.
    hasHousing: true,
    hasChildcare: true,
    hasCarer: true,
    hasCapital: true,
    hasPensionIncome: true,
    hasSelfEmployment: true,
    // Net income in policyengine-uk adds the UC housing element but never
    // subtracts rent, so a two-household comparison would collect housing
    // support twice and pay rent zero times. Net income is reported after
    // housing costs for the UK to keep the comparison honest.
    deductRentFromNetIncome: true,
    aggregateMap: {
      householdNetIncome: "household_net_income",
      householdNetIncomeWithHealth: "household_net_income", // No separate health metric in UK
      householdBenefits: "household_benefits",
      householdRefundableCredits: null,
      householdTaxBeforeCredits: "household_tax",
      healthcareBenefitValue: null,
      householdRefundableStateCredits: null,
    },
    gridConfig: [
      // deductRent: rent is subtracted from every scenario so the heatmap
      // agrees with the metric cards, which also report after housing costs.
      { variable: "household_net_income", tab: "net income", deductRent: true },
      { variable: "household_benefits", tab: "benefits" },
      { variable: "household_tax", tab: "tax", invertDelta: true },
    ],
  },
  us: {
    id: "us",
    name: "United States",
    currencySymbol: "$",
    apiPath: "/us/calculate",
    defaultYear: "2026",
    availableYears: ["2026", "2027", "2028"],
    defaultAge: 40,
    defaultRegion: "CA",
    regions: US_REGIONS,
    regionLabel: "State",
    regionVariable: "state_name",
    metadata: usMetadata,
    entityContainers: {
      household: { key: "households", name: "your household" },
      tax_unit: { key: "tax_units", name: "your tax unit" },
      spm_unit: { key: "spm_units", name: "your spm_unit" },
    },
    tabs: ["summary", "taxes", "benefits", "credits"],
    hasCredits: true,
    hasStateCredits: true,
    hasDisability: true,
    hasPregnancy: true,
    hasESI: true,
    hasNYC: true,
    // Maps standard aggregate keys to variable names in the API response
    aggregateMap: {
      householdNetIncome: "household_net_income",
      householdNetIncomeWithHealth: "household_net_income_including_health_benefits",
      householdBenefits: "household_benefits",
      householdRefundableCredits: "household_refundable_tax_credits",
      householdTaxBeforeCredits: "household_tax_before_refundable_credits",
      healthcareBenefitValue: "healthcare_benefit_value",
      householdRefundableStateCredits: "household_refundable_state_tax_credits",
    },
    // Grid variables for heatmap, in order
    gridConfig: [
      { variable: "household_net_income", tab: "net income" },
      { variable: "household_net_income_including_health_benefits", tab: "net income (with healthcare)" },
      { variable: "household_benefits", tab: "benefits" },
      { variable: "household_refundable_tax_credits", tab: "refundable tax credits" },
      { variable: "household_tax_before_refundable_credits", tab: "tax before refundable credits", invertDelta: true },
      { variable: "healthcare_benefit_value", tab: "healthcare benefits" },
      { variable: "household_refundable_state_tax_credits", tab: "state credits" },
    ],
  },
};

// The UK is the default: this tool's main audience is the UK couple penalty,
// and the US route is served with an explicit ?country=us.
export const DEFAULT_COUNTRY = "uk";

// Shared links written before the country was recorded in the hash are always
// US: those hashes predate the UK route. Decoding them with DEFAULT_COUNTRY
// would silently reinterpret a US state as a UK one.
export const LEGACY_HASH_COUNTRY = "us";

export function getCountry(id) {
  return COUNTRIES[id] || COUNTRIES[DEFAULT_COUNTRY];
}
